import React from 'react'

const AutoCad = () => {
    return (
        <div className='container single-course mb-5 mt-sm-5'>
            <h2><u>AUTOCAD Course:</u></h2>
            <p><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>1. Creating a Simple Drawing&nbsp; </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Getting Started with AutoCAD, Starting AutoCAD, AutoCAD's Screen Layout, Working with Commands, Opening an Existing Drawing File, Saving Your Work. </span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>Basic Drawing &amp; Editing Commands </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Drawing Lines, Erasing Objects, Drawing Lines with Polar Tracking, Drawing Rectangles, Drawing Circles, Viewing Your Drawing, Undoing and Redoing Actions.&nbsp;</span></span></span></p>
            <p><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>2. Making Your Drawings More Precise </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Drawing Precision in AutoCAD</span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><em>&nbsp; </em></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Using Object Snap, Object Snap Overrides, Polar Tracking Settings, Object Snap Tracking, Drawing with SNAP and GRID, Making Changes in Your Drawing: Selecting Objects for Editing , Moving Objects, Copying Objects, Rotating Objects, Scaling Objects, Mirroring Objects, Editing Objects with Grips.&nbsp;</span></span></span></p>
            <p><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>3. Drawing Organization and Information&nbsp; </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Organizing Your Drawing with Layers, Creating New Drawings With Templates, What are Layers? Layer State, Changing an Object's Layer. </span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><em>Advanced Object Types: </em></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Drawing Arcs, Drawing Polylines, Editing Polylines , Drawing Polygons, Drawing Ellipses, Getting Information From Your Drawing, Measuring Objects, Working with Properties.&nbsp;</span></span></span></p>
            <p><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>4. Creating More Complex Objects&nbsp; </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Advanced Editing Commands, Trimming and Extending, Stretching Objects , Creating Fillets and Chamfers, Offsetting Objects, Creating Arrays of Objects, Inserting Blocks , What are Blocks, Inserting Blocks from Tool Palettes?, Inserting Blocks using Insert, Inserting Blocks with Design Center.</span></span></span></p>
            <p><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>5. Preparing to Print </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Setting Up a Layout, Printing Concepts, Creating Viewports, Setting up Layouts&nbsp;</span></span></span></p>
            <p><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Guidelines for Layouts, Printing Your Drawing, Printing Layouts, Printing a Check Plot.&nbsp; </span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>
                <br />
                6. Annotating Your Drawing&nbsp; </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Text , Working with Annotations, Adding Text in a Drawing , Modifying Multiline Text&nbsp; Formatting Multiline Text , Hatching, Hatching, Adding Dimensions, Dimensioning Concepts, Adding Linear Dimensions, Adding Radial and Angular Dimensions, Editing Dimensions, Adding Notes to Your Drawing.&nbsp; </span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>7. Beyond the Basics&nbsp; </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Working Effectively with AutoCAD, Setting up the Interface, Using the Keyboard Effectively, Working in Multiple Drawings, Using Grips Effectively, Additional Layer Tools, Accurate Positioning, Coordinate Entry, Locating Points with Tracking, Construction Lines, Placing Reference Points.&nbsp; </span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}><strong>8. Creating and Organizing Blocks </strong></span></span></span><span style={{ fontSize: '11pt' }}><span style={{ fontFamily: 'Calibri,sans-serif' }}><span style={{ color: '#000000' }}>Creating Blocks,&nbsp; Creating Blocks, Editing Blocks, Removing Unused Elements, Blocks in Tool Palettes, Adding Blocks to Tool Palettes, Modifying Tool Properties in Tool Palettes.</span></span></span></p>
        </div>
    )
}

export default AutoCad