import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* feature */}
      <div className="site-section">
        <div className="container">
          <div className="row mb-5 justify-content-center text-center">
            <div className="col-lg-4 mb-5">
              <h2 className="section-title-underline mb-5">
                <span>Why Academics Works</span>
              </h2>
            </div>
          </div>
          <div className="row">
            <div className="col-lg-4 col-md-6 mb-4 mb-lg-0">
              <div className="feature-1 border">
                <div className="icon-wrapper bg-primary">
                  <span className="flaticon-mortarboard text-white" />
                </div>
                <div className="feature-1-content">
                  <h2>Personalize Learning</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit
                    morbi hendrerit elit
                  </p>
                  <p>
                    <a href="#" className="btn btn-primary px-4 rounded-0">
                      Learn More
                    </a>
                  </p>
                </div>
              </div>
            </div>
            <div className="col-lg-4 col-md-6 mb-4 mb-lg-0">
              <div className="feature-1 border">
                <div className="icon-wrapper bg-primary">
                  <span className="flaticon-school-material text-white" />
                </div>
                <div className="feature-1-content">
                  <h2>Trusted Courses</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit
                    morbi hendrerit elit
                  </p>
                  <p>
                    <a href="#" className="btn btn-primary px-4 rounded-0">
                      Learn More
                    </a>
                  </p>
                </div>
              </div>
            </div>
            <div className="col-lg-4 col-md-6 mb-4 mb-lg-0">
              <div className="feature-1 border">
                <div className="icon-wrapper bg-primary">
                  <span className="flaticon-library text-white" />
                </div>
                <div className="feature-1-content">
                  <h2>Tools for Students</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit
                    morbi hendrerit elit
                  </p>
                  <p>
                    <a href="#" className="btn btn-primary px-4 rounded-0">
                      Learn More
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* about our University */}
      <div
        className="section-bg style-1"
        style={{ backgroundImage: 'url("/assets/images/about_1.jpg")' }}
      >
        <div className="container">
          <div className="row">
            <div className="col-lg-4">
              <h2 className="section-title-underline style-2">
                <span>About Our University</span>
              </h2>
            </div>
            <div className="col-lg-8">
              <p className="lead">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem
                nesciunt quaerat ad reiciendis perferendis voluptate fugiat sunt
                fuga error totam.
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Voluptatibus assumenda omnis tempora ullam alias amet eveniet
                voluptas, incidunt quasi aut officiis porro ad, expedita saepe
                necessitatibus rem debitis architecto dolore? Nam omnis sapiente
                placeat blanditiis voluptas dignissimos, itaque fugit a
                laudantium adipisci dolorem enim ipsum cum molestias? Quod quae
                molestias modi fugiat quisquam. Eligendi recusandae officiis
                debitis quas beatae aliquam?
              </p>
              <p>
                <a href="#">Read more</a>
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* testimonial */}
      <div className="site-section">
        <div className="container">
          <div className="row mb-5">
            <div className="col-lg-4">
              <h2 className="section-title-underline">
                <span>Testimonials</span>
              </h2>
            </div>
          </div>
          <div className="owl-slide owl-carousel">
            <div className="ftco-testimonial-1">
              <div className="ftco-testimonial-vcard d-flex align-items-center mb-4">
                <img
                  src="assets/images/person_1.jpg"
                  alt="Image"
                  className="img-fluid mr-3"
                />
                <div>
                  <h3>Allison Holmes</h3>
                  <span>Designer</span>
                </div>
              </div>
              <div>
                <p>
                  “Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Neque, mollitia. Possimus mollitia nobis libero quidem aut
                  tempore dolore iure maiores, perferendis, provident numquam
                  illum nisi amet necessitatibus. A, provident aperiam!”
                </p>
              </div>
            </div>
            <div className="ftco-testimonial-1">
              <div className="ftco-testimonial-vcard d-flex align-items-center mb-4">
                <img
                  src="assets/images/person_2.jpg"
                  alt="Image"
                  className="img-fluid mr-3"
                />
                <div>
                  <h3>Allison Holmes</h3>
                  <span>Designer</span>
                </div>
              </div>
              <div>
                <p>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Neque, mollitia. Possimus mollitia nobis libero quidem aut
                  tempore dolore iure maiores, perferendis, provident numquam
                  illum nisi amet necessitatibus. A, provident aperiam!
                </p>
              </div>
            </div>
            <div className="ftco-testimonial-1">
              <div className="ftco-testimonial-vcard d-flex align-items-center mb-4">
                <img
                  src="assets/images/person_4.jpg"
                  alt="Image"
                  className="img-fluid mr-3"
                />
                <div>
                  <h3>Allison Holmes</h3>
                  <span>Designer</span>
                </div>
              </div>
              <div>
                <p>
                  “Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Neque, mollitia. Possimus mollitia nobis libero quidem aut
                  tempore dolore iure maiores, perferendis, provident numquam
                  illum nisi amet necessitatibus. A, provident aperiam!”
                </p>
              </div>
            </div>
            <div className="ftco-testimonial-1">
              <div className="ftco-testimonial-vcard d-flex align-items-center mb-4">
                <img
                  src="assets/images/person_3.jpg"
                  alt="Image"
                  className="img-fluid mr-3"
                />
                <div>
                  <h3>Allison Holmes</h3>
                  <span>Designer</span>
                </div>
              </div>
              <div>
                <p>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Neque, mollitia. Possimus mollitia nobis libero quidem aut
                  tempore dolore iure maiores, perferendis, provident numquam
                  illum nisi amet necessitatibus. A, provident aperiam!
                </p>
              </div>
            </div>
            <div className="ftco-testimonial-1">
              <div className="ftco-testimonial-vcard d-flex align-items-center mb-4">
                <img
                  src="assets/images/person_2.jpg"
                  alt="Image"
                  className="img-fluid mr-3"
                />
                <div>
                  <h3>Allison Holmes</h3>
                  <span>Designer</span>
                </div>
              </div>
              <div>
                <p>
                  “Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Neque, mollitia. Possimus mollitia nobis libero quidem aut
                  tempore dolore iure maiores, perferendis, provident numquam
                  illum nisi amet necessitatibus. A, provident aperiam!”
                </p>
              </div>
            </div>
            <div className="ftco-testimonial-1">
              <div className="ftco-testimonial-vcard d-flex align-items-center mb-4">
                <img
                  src="assets/images/person_4.jpg"
                  alt="Image"
                  className="img-fluid mr-3"
                />
                <div>
                  <h3>Allison Holmes</h3>
                  <span>Designer</span>
                </div>
              </div>
              <div>
                <p>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Neque, mollitia. Possimus mollitia nobis libero quidem aut
                  tempore dolore iure maiores, perferendis, provident numquam
                  illum nisi amet necessitatibus. A, provident aperiam!
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* our Philosphy */}
      <div
        className="section-bg style-1"
        style={{ backgroundImage: 'url("/assets/images/hero_1.jpg")' }}
      >
        <div className="container">
          <div className="row">
            <div className="col-lg-4 col-md-6 mb-5 mb-lg-0">
              <span className="icon flaticon-mortarboard" />
              <h3>Our Philosphy</h3>
              <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Reiciendis recusandae, iure repellat quis delectus ea? Dolore,
                amet reprehenderit.
              </p>
            </div>
            <div className="col-lg-4 col-md-6 mb-5 mb-lg-0">
              <span className="icon flaticon-school-material" />
              <h3>Academics Principle</h3>
              <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Reiciendis recusandae, iure repellat quis delectus ea? Dolore,
                amet reprehenderit.
              </p>
            </div>
            <div className="col-lg-4 col-md-6 mb-5 mb-lg-0">
              <span className="icon flaticon-library" />
              <h3>Key of Success</h3>
              <p>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Reiciendis recusandae, iure repellat quis delectus ea? Dolore,
                amet reprehenderit.
              </p>
            </div>
          </div>
        </div>
      </div>
      {/* news updates */}
      <div className="news-updates">
        <div className="container">
          <div className="row">
            <div className="col-lg-9">
              <div className="section-heading">
                <h2 className="text-black">News &amp; Updates</h2>
                <a href="#">Read All News</a>
              </div>
              <div className="row">
                <div className="col-lg-6">
                  <div className="post-entry-big">
                    <a href="news-single.html" className="img-link">
                      <Image
                        src="/assets/images/blog_large_1.jpg"
                        alt="Image"
                        className="img-fluid"
                        width="384px"
                        height="256px"
                        // layout="responsive"
                      />
                    </a>
                    <div className="post-content">
                      <div className="post-meta">
                        <a href="#">June 6, 2019</a>
                        <span className="mx-1">/</span>
                        <a href="#">Admission</a>, <a href="#">Updates</a>
                      </div>
                      <h3 className="post-heading">
                        <a href="news-single.html">
                          Campus Camping and Learning Session
                        </a>
                      </h3>
                    </div>
                  </div>
                </div>
                <div className="col-lg-6">
                  <div className="post-entry-big horizontal d-flex mb-4">
                    <a href="news-single.html" className="img-link mr-4">
                      <img
                        src="assets/images/blog_1.jpg"
                        alt="Image"
                        className="img-fluid"
                      />
                    </a>
                    <div className="post-content">
                      <div className="post-meta">
                        <a href="#">June 6, 2019</a>
                        <span className="mx-1">/</span>
                        <a href="#">Admission</a>, <a href="#">Updates</a>
                      </div>
                      <h3 className="post-heading">
                        <a href="news-single.html">
                          Campus Camping and Learning Session
                        </a>
                      </h3>
                    </div>
                  </div>
                  <div className="post-entry-big horizontal d-flex mb-4">
                    <a href="news-single.html" className="img-link mr-4">
                      <img
                        src="assets/images/blog_2.jpg"
                        alt="Image"
                        className="img-fluid"
                      />
                    </a>
                    <div className="post-content">
                      <div className="post-meta">
                        <a href="#">June 6, 2019</a>
                        <span className="mx-1">/</span>
                        <a href="#">Admission</a>, <a href="#">Updates</a>
                      </div>
                      <h3 className="post-heading">
                        <a href="news-single.html">
                          Campus Camping and Learning Session
                        </a>
                      </h3>
                    </div>
                  </div>
                  <div className="post-entry-big horizontal d-flex mb-4">
                    <a href="news-single.html" className="img-link mr-4">
                      <img
                        src="assets/images/blog_1.jpg"
                        alt="Image"
                        className="img-fluid"
                      />
                    </a>
                    <div className="post-content">
                      <div className="post-meta">
                        <a href="#">June 6, 2019</a>
                        <span className="mx-1">/</span>
                        <a href="#">Admission</a>, <a href="#">Updates</a>
                      </div>
                      <h3 className="post-heading">
                        <a href="news-single.html">
                          Campus Camping and Learning Session
                        </a>
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-3">
              <div className="section-heading">
                <h2 className="text-black">Campus Videos</h2>
                <a href="#">View All Videos</a>
              </div>
              <a
                href="https://vimeo.com/45830194"
                className="video-1 mb-4"
                data-fancybox
                data-ratio={2}
              >
                <span className="play">
                  <span className="icon-play" />
                </span>
                <img
                  src="assets/images/course_5.jpg"
                  alt="Image"
                  className="img-fluid"
                />
              </a>
              <a
                href="https://vimeo.com/45830194"
                className="video-1 mb-4"
                data-fancybox
                data-ratio={2}
              >
                <span className="play">
                  <span className="icon-play" />
                </span>
                <img
                  src="assets/images/course_5.jpg"
                  alt="Image"
                  className="img-fluid"
                />
              </a>
            </div>
          </div>
        </div>
      </div>
      {/* CTA subscribe */}
      <div
        className="site-section ftco-subscribe-1"
        style={{ backgroundImage: 'url("assets/images/bg_1.jpg")' }}
      >
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-7">
              <h2>Subscribe to us!</h2>
              <p>
                Far far away, behind the word mountains, far from the countries
                Vokalia and Consonantia,
              </p>
            </div>
            <div className="col-lg-5">
              <form className="d-flex">
                <input
                  type="text"
                  className="rounded form-control mr-2 py-3"
                  placeholder="Enter your email"
                />
                <button
                  className="btn btn-primary rounded py-3 px-4"
                  type="submit"
                >
                  Send
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
